### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pandademic** [Pandademic/ais#1]
## TODO
- [x] Install yaourt.
- [x] Allow both BIOS and UEFI to run this script.
- [x] Ask if user want to create user or not.
- [x] Install X Server.
- [x] Install Sublime Text.
- [x] Install necessary packages (web browser, git, etc.).
- [x] Install fonts (Adobe Source Code, Hack).
- [ ] Configure full screen tty console in Arch.
- [x] Figure out why Arch does not work after installing KDE/SDDM and Deepin/lightdm.
- [x] Copy, paste, share clipboard from guest to host.
- [x] At the end of installation process, obviously, `rm configure.sh` is not working. Figure it out some time. (Silly mistake: the directory which the script is working on is /, the remove command should be `rm /configure.sh` instead of `rm configure.sh`.)
